{
    "search_metadata": {
        "id": "67359d7c66d9950a646e29eb",
        "status": "Success",
        "json_endpoint": "https://serpapi.com/searches/7589baf242131e8f/67359d7c66d9950a646e29eb.json",
        "created_at": "2024-11-14 06:49:32 UTC",
        "processed_at": "2024-11-14 06:49:32 UTC",
        "google_url": "https://www.google.com/search?q=what+is+the+best+way+to+communiate+these+Microsoft&oq=what+is+the+best+way+to+communiate+these+Microsoft&sourceid=chrome&ie=UTF-8",
        "raw_html_file": "https://serpapi.com/searches/7589baf242131e8f/67359d7c66d9950a646e29eb.html",
        "total_time_taken": 1.85,
    },
    "search_parameters": {
        "engine": "google",
        "q": "what is the best way to communiate these Microsoft",
        "google_domain": "google.com",
        "device": "desktop",
    },
    "search_information": {
        "query_displayed": "what is the best way to communiate these Microsoft",
        "total_results": 524000000,
        "time_taken_displayed": 0.37,
        "organic_results_state": "Some results for exact spelling but showing fixed spelling",
        "spelling_fix": "what is the best way to communicate these Microsoft",
        "showing_results_for": "what is the best way to communicate these Microsoft",
    },
    "inline_videos": [
        {
            "position": 1,
            "title": "Your Guide To Better Communication in Microsoft Teams",
            "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0",
            "thumbnail": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/d4db06be3477c451877796a6f68a367fe288852bb2681120c2e397dbc92b75f5.jpeg",
            "channel": "Commsverse",
            "duration": "49:31",
            "platform": "YouTube",
            "date": "Feb 15, 2021",
            "key_moments": [
                {
                    "time": "00:04",
                    "title": "Introduction",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=4",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn7a4oB9YxJOr9srxK5QVC5lNahKNuHDwZTfedhDnJVw&s",
                },
                {
                    "time": "06:24",
                    "title": "Audience size",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=384",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuVrqp2aHb1XAyA3C76RmquuGvVl4ZITpqODhuhNiloQ&s",
                },
                {
                    "time": "12:48",
                    "title": "Tagging additional people",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=768",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfIDEPznz2mpgLyrTeM0SBNi5yF4eBKrxiXj3UUusGdA&s",
                },
                {
                    "time": "16:26",
                    "title": "Reactions",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=986",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ9rssDN7T6eTjVFGR_EwbdgMRQ4ENduO-5LImPWwMZw&s",
                },
                {
                    "time": "22:20",
                    "title": "Deleting files in private chat",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=1340",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB-xb0K2DbjnmFaLLa_kSeIwUtWA1xFdxTTKJWg9jEcg&s",
                },
                {
                    "time": "27:13",
                    "title": "Private Channels",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=1633",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX344-8h8KBrO2kxUi-ZokvsLQgFXtj17XUTcgbRqeTA&s",
                },
                {
                    "time": "33:33",
                    "title": "Pro-tip: Reply block",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=2013",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6zfyD_stE5uli29e2SQLInxLh_N6rME1-Curg_UaDSg&s",
                },
                {
                    "time": "38:33",
                    "title": "Mute notifications",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=2313",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2D4jVBNdKxIXl6JTe1rNxhsX97Ihc1ERDPs4nbKCIug&s",
                },
                {
                    "time": "43:40",
                    "title": "Meeting notifications",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=2620",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqY5Az2hWeho0snP7aojTnelXNmUjAbTKqAvHL7e7w2Q&s",
                },
                {
                    "time": "49:00",
                    "title": "Wrap up",
                    "link": "https://www.youtube.com/watch?v=r0VMJoC6qC0&t=2940",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkzqbSfroUQhh564IkwPtFUf0_uGLCF98DvBTXVNaI8w&s",
                },
            ],
        },
        {
            "position": 2,
            "title": "Teams Communication Best Practices",
            "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ",
            "thumbnail": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/d4db06be3477c451dd9843044fccd30384af4638b201fe154d05ef02d668b779.jpeg",
            "channel": "CTC Productivity",
            "duration": "44:40",
            "platform": "YouTube",
            "date": "Oct 15, 2022",
            "key_moments": [
                {
                    "time": "02:22",
                    "title": "Streamline Reporting",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=142",
                },
                {
                    "time": "06:52",
                    "title": "Broad Communication",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=412",
                },
                {
                    "time": "11:02",
                    "title": "When Did Email Really Become Mainstream",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=662",
                },
                {
                    "time": "16:59",
                    "title": "Preferred Mode of Communication",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=1019",
                },
                {
                    "time": "20:14",
                    "title": "Teams Chat",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=1214",
                },
                {
                    "time": "23:05",
                    "title": "Format Your Chat",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=1385",
                },
                {
                    "time": "30:04",
                    "title": "Teams Posts",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=1804",
                },
                {
                    "time": "35:52",
                    "title": "Replying",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=2152",
                },
                {
                    "time": "38:48",
                    "title": "Posting to Channels",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=2328",
                },
                {
                    "time": "41:19",
                    "title": "One Schedule Meetings as Channel Meetings",
                    "link": "https://www.youtube.com/watch?v=utwhX3rS1aQ&t=2479",
                },
            ],
        },
        {
            "position": 3,
            "title": "Communicate like a pro using Microsoft Teams",
            "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA",
            "thumbnail": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/d4db06be3477c451e5a4419bbb7057f374344cf860eb565f94a9e3930a5d61a9.jpeg",
            "channel": "Storyals",
            "duration": "13:54",
            "platform": "YouTube",
            "date": "Jan 31, 2020",
            "key_moments": [
                {
                    "time": "00:00",
                    "title": "Succeed in the Digital Workplace Intro",
                    "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA&t=0",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuIhoMtakyn-8gsa1fYLI3jbdet3-6pp8Dms3xlo7M2g&s",
                },
                {
                    "time": "00:32",
                    "title": "Communicate like a pro using Teams intro",
                    "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA&t=32",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwfFSGbxQRv7sQijFU8gz_2ExfNBnwXt26dlcA8mDrAQ&s",
                },
                {
                    "time": "01:41",
                    "title": "Part 1: Understand what type of messaging to use when",
                    "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA&t=101",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDOtbjaVnIFsJShngtXIFt8dq9Msy7sF6TaRLX1eJ9Ag&s",
                },
                {
                    "time": "04:36",
                    "title": 'Part 2: Leverage "@mentions" to get people\'s attention',
                    "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA&t=276",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROrw-bEuOgc_mfR4f5DrqNBN1qacrxWGUB6ib_tfWc7Q&s",
                },
                {
                    "time": "06:39",
                    "title": "Part 3: Finetune your notification settings",
                    "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA&t=399",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC3IBfVYOmKmn8_C1jrRsQSO1V5RRU5dAlUrJTW6zrhA&s",
                },
                {
                    "time": "08:48",
                    "title": "Part 4: Select which channels to actively engage in",
                    "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA&t=528",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAFR8Sp_EIn-6a4GwNYVR_0okR3K8XOt2alMqah8YeA&s",
                },
                {
                    "time": "10:28",
                    "title": "Part 5: Actively use your presence to show availability",
                    "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA&t=628",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSckBMe-DjLcS-a-hLhkahCWUxIGtokn8UUHq1Zsianaw&s",
                },
                {
                    "time": "12:52",
                    "title": "Conclusion and about Storyals",
                    "link": "https://www.youtube.com/watch?v=PoLyP8lQ6eA&t=772",
                    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRffIsUkUBqFzdbzmaDyAoht5ykZ0a-XJkfBKccy0gIQ&s",
                },
            ],
        },
    ],
    "related_questions": [
        {
            "question": "How can I communicate with Microsoft?",
            "snippet": "Open a service request in the Microsoft 365 admin center. This service is free.",
            "title": "Contact Us - Microsoft Support",
            "link": "https://support.microsoft.com/en-us/contactus#:~:text=Open%20a%20service%20request%20in,This%20service%20is%20free.",
            "displayed_link": "https://support.microsoft.com › en-us › contactus",
            "source_logo": null,
            "next_page_token": "eyJvbnMiOiIxMDA0MSIsImZjIjoiRXFFQkNtSkJTa2M1U210TlRUaFlPRlJYTTFObGRrb3RkbDh5Vm5OVFQwcG9SRkV3WTFGT1VsOXlPR1J5UWxGS09VOXFZeTA1U1RBNE1WWk1lbGxRUW1oTVlXTkNORkpJZDJKVVRVUkdiVGhvUmtKc1R6bHNkalpqTm5wMU15MXFhMncwU2xoVGR4SVhabG93TVZwZmVYTk5USFZHZDJKclVERlpWSEEyVVRBYUlrRkdXSEpGWTI5MGJVWlhWMlZqWW5STGNESnVVMHAwYjJWU2RWRktTa2N0VkZFIiwiZmN2IjoiMyIsImVpIjoiZlowMVpfeXNNTHVGd2JrUDFZVHA2UTAiLCJxYyI6IkNqTjNhR0YwSUdseklIUm9aU0JpWlhOMElIZGhlU0IwYnlCamIyMXRkVzVwWTJGMFpTQjBhR1Z6WlNCdGFXTnliM052Wm5RUUFIMFYzVElfIiwicXVlc3Rpb24iOiJIb3cgY2FuIEkgY29tbXVuaWNhdGUgd2l0aCBNaWNyb3NvZnQ/IiwibGsiOiJHaVJvYjNjZ1kyRnVJR2tnWTI5dGJYVnVhV05oZEdVZ2QybDBhQ0J0YVdOeWIzTnZablEiLCJicyI6ImM0WFBzUXJDTUJBR1lOemtKc2VRNlFiYnVxalFYYkxxNENKRjU5S2tKR0I2eGFTVWpyNkFiLWE3LUFpMnFMU2k2UDdkX184SE93aldWR09XRnJqQmpLeXRDcE9sWG1GdHZNYXR5VTdrS1BlQ1hXVWM4cWwtV3ZOcDdjdUNoTVZCcHg1OVV5cWtmRUFORlNoSnVUNFlLNmNFdXpYeGtzX3JQMGQyZUFSN2lMcmxrZ1poeXBaSGFsUnJCX01FTzZfaUdRXzFROXZmR2hJSXUxeFBieS0yR19xYVJLWFdDWFlaeHhFUDlGZmN0X2dPVDBaMyIsImlkIjoiZmNfZlowMVpfeXNNTHVGd2JrUDFZVHA2UTBfMSJ9",
            "serpapi_link": "https://serpapi.com/search.json?device=desktop&engine=google_related_questions&google_domain=google.com&next_page_token=eyJvbnMiOiIxMDA0MSIsImZjIjoiRXFFQkNtSkJTa2M1U210TlRUaFlPRlJYTTFObGRrb3RkbDh5Vm5OVFQwcG9SRkV3WTFGT1VsOXlPR1J5UWxGS09VOXFZeTA1U1RBNE1WWk1lbGxRUW1oTVlXTkNORkpJZDJKVVRVUkdiVGhvUmtKc1R6bHNkalpqTm5wMU15MXFhMncwU2xoVGR4SVhabG93TVZwZmVYTk5USFZHZDJKclVERlpWSEEyVVRBYUlrRkdXSEpGWTI5MGJVWlhWMlZqWW5STGNESnVVMHAwYjJWU2RWRktTa2N0VkZFIiwiZmN2IjoiMyIsImVpIjoiZlowMVpfeXNNTHVGd2JrUDFZVHA2UTAiLCJxYyI6IkNqTjNhR0YwSUdseklIUm9aU0JpWlhOMElIZGhlU0IwYnlCamIyMXRkVzVwWTJGMFpTQjBhR1Z6WlNCdGFXTnliM052Wm5RUUFIMFYzVElfIiwicXVlc3Rpb24iOiJIb3cgY2FuIEkgY29tbXVuaWNhdGUgd2l0aCBNaWNyb3NvZnQ%2FIiwibGsiOiJHaVJvYjNjZ1kyRnVJR2tnWTI5dGJYVnVhV05oZEdVZ2QybDBhQ0J0YVdOeWIzTnZablEiLCJicyI6ImM0WFBzUXJDTUJBR1lOemtKc2VRNlFiYnVxalFYYkxxNENKRjU5S2tKR0I2eGFTVWpyNkFiLWE3LUFpMnFMU2k2UDdkX184SE93aldWR09XRnJqQmpLeXRDcE9sWG1GdHZNYXR5VTdrS1BlQ1hXVWM4cWwtV3ZOcDdjdUNoTVZCcHg1OVV5cWtmRUFORlNoSnVUNFlLNmNFdXpYeGtzX3JQMGQyZUFSN2lMcmxrZ1poeXBaSGFsUnJCX01FTzZfaUdRXzFROXZmR2hJSXUxeFBieS0yR19xYVJLWFdDWFlaeHhFUDlGZmN0X2dPVDBaMyIsImlkIjoiZmNfZlowMVpfeXNNTHVGd2JrUDFZVHA2UTBfMSJ9",
        },
        {
            "question": "What type of communication does Microsoft use?",
            "snippet": "Delivering communications internally at Microsoft with Microsoft Viva Amplify. Microsoft Viva Amplify provides communicators a single platform for creating, delivering, and measuring the impact of the messages they send to employees.",
            "title": "Delivering communications internally at Microsoft with Microsoft Viva ...",
            "date": "Mar 18, 2024",
            "link": "https://www.microsoft.com/insidetrack/blog/delivering-communications-internally-at-microsoft-with-microsoft-viva-amplify/#:~:text=Delivering%20communications%20internally%20at%20Microsoft%20with%20Microsoft%20Viva%20Amplify,-March%2018%2C%202024&text=Microsoft%20Viva%20Amplify%20provides%20communicators,messages%20they%20send%20to%20employees.",
            "displayed_link": "https://www.microsoft.com › insidetrack › blog › deliver...",
            "source_logo": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/d82d59af0f2f63290953b6c9f1f14061a576c1ec46f5a555dc1c3a637d64bdfb.png",
            "next_page_token": "eyJvbnMiOiIxMDA0MSIsImZjIjoiRXFFQkNtSkJTa2M1U210TlRUaFlPRlJYTTFObGRrb3RkbDh5Vm5OVFQwcG9SRkV3WTFGT1VsOXlPR1J5UWxGS09VOXFZeTA1U1RBNE1WWk1lbGxRUW1oTVlXTkNORkpJZDJKVVRVUkdiVGhvUmtKc1R6bHNkalpqTm5wMU15MXFhMncwU2xoVGR4SVhabG93TVZwZmVYTk5USFZHZDJKclVERlpWSEEyVVRBYUlrRkdXSEpGWTI5MGJVWlhWMlZqWW5STGNESnVVMHAwYjJWU2RWRktTa2N0VkZFIiwiZmN2IjoiMyIsImVpIjoiZlowMVpfeXNNTHVGd2JrUDFZVHA2UTAiLCJxYyI6IkNqTjNhR0YwSUdseklIUm9aU0JpWlhOMElIZGhlU0IwYnlCamIyMXRkVzVwWTJGMFpTQjBhR1Z6WlNCdGFXTnliM052Wm5RUUFIMFYzVElfIiwicXVlc3Rpb24iOiJXaGF0IHR5cGUgb2YgY29tbXVuaWNhdGlvbiBkb2VzIE1pY3Jvc29mdCB1c2U/IiwibGsiOiJHaTEzYUdGMElIUjVjR1VnYjJZZ1kyOXRiWFZ1YVdOaGRHbHZiaUJrYjJWeklHMXBZM0p2YzI5bWRDQjFjMlUiLCJicyI6ImM0WFBzUXJDTUJBR1lOemtKc2VRNlFiYnVxalFYYkxxNENKRjU5S2tKR0I2eGFTVWpyNkFiLWE3LUFpMnFMU2k2UDdkX184SE93aldWR09XRnJqQmpLeXRDcE9sWG1GdHZNYXR5VTdrS1BlQ1hXVWM4cWwtV3ZOcDdjdUNoTVZCcHg1OVV5cWtmRUFORlNoSnVUNFlLNmNFdXpYeGtzX3JQMGQyZUFSN2lMcmxrZ1poeXBaSGFsUnJCX01FTzZfaUdRXzFROXZmR2hJSXUxeFBieS0yR19xYVJLWFdDWFlaeHhFUDlGZmN0X2dPVDBaMyIsImlkIjoiZmNfZlowMVpfeXNNTHVGd2JrUDFZVHA2UTBfMSJ9",
            "serpapi_link": "https://serpapi.com/search.json?device=desktop&engine=google_related_questions&google_domain=google.com&next_page_token=eyJvbnMiOiIxMDA0MSIsImZjIjoiRXFFQkNtSkJTa2M1U210TlRUaFlPRlJYTTFObGRrb3RkbDh5Vm5OVFQwcG9SRkV3WTFGT1VsOXlPR1J5UWxGS09VOXFZeTA1U1RBNE1WWk1lbGxRUW1oTVlXTkNORkpJZDJKVVRVUkdiVGhvUmtKc1R6bHNkalpqTm5wMU15MXFhMncwU2xoVGR4SVhabG93TVZwZmVYTk5USFZHZDJKclVERlpWSEEyVVRBYUlrRkdXSEpGWTI5MGJVWlhWMlZqWW5STGNESnVVMHAwYjJWU2RWRktTa2N0VkZFIiwiZmN2IjoiMyIsImVpIjoiZlowMVpfeXNNTHVGd2JrUDFZVHA2UTAiLCJxYyI6IkNqTjNhR0YwSUdseklIUm9aU0JpWlhOMElIZGhlU0IwYnlCamIyMXRkVzVwWTJGMFpTQjBhR1Z6WlNCdGFXTnliM052Wm5RUUFIMFYzVElfIiwicXVlc3Rpb24iOiJXaGF0IHR5cGUgb2YgY29tbXVuaWNhdGlvbiBkb2VzIE1pY3Jvc29mdCB1c2U%2FIiwibGsiOiJHaTEzYUdGMElIUjVjR1VnYjJZZ1kyOXRiWFZ1YVdOaGRHbHZiaUJrYjJWeklHMXBZM0p2YzI5bWRDQjFjMlUiLCJicyI6ImM0WFBzUXJDTUJBR1lOemtKc2VRNlFiYnVxalFYYkxxNENKRjU5S2tKR0I2eGFTVWpyNkFiLWE3LUFpMnFMU2k2UDdkX184SE93aldWR09XRnJqQmpLeXRDcE9sWG1GdHZNYXR5VTdrS1BlQ1hXVWM4cWwtV3ZOcDdjdUNoTVZCcHg1OVV5cWtmRUFORlNoSnVUNFlLNmNFdXpYeGtzX3JQMGQyZUFSN2lMcmxrZ1poeXBaSGFsUnJCX01FTzZfaUdRXzFROXZmR2hJSXUxeFBieS0yR19xYVJLWFdDWFlaeHhFUDlGZmN0X2dPVDBaMyIsImlkIjoiZmNfZlowMVpfeXNNTHVGd2JrUDFZVHA2UTBfMSJ9",
        },
        {
            "question": "How do Microsoft employees communicate?",
            "snippet": "Microsoft Viva Employee Communications and Communities Viva Engage connects everyone at your organization through employee communities and conversations. Viva Connections helps employees explore news, join conversations, and connect across the organization.",
            "title": "Employee Communication Platform | Microsoft Viva Engage",
            "link": "https://www.microsoft.com/en-us/microsoft-viva/engage#:~:text=Microsoft%20Viva%20Employee%20Communications%20and%20Communities&text=Viva%20Engage%20connects%20everyone%20at,and%20connect%20across%20the%20organization.",
            "displayed_link": "https://www.microsoft.com › en-us › engage",
            "source_logo": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/d82d59af0f2f63290953b6c9f1f140615397b38f9bb3cfb460bc1b112e9aa9ad.png",
            "next_page_token": "eyJvbnMiOiIxMDA0MSIsImZjIjoiRXFFQkNtSkJTa2M1U210TlRUaFlPRlJYTTFObGRrb3RkbDh5Vm5OVFQwcG9SRkV3WTFGT1VsOXlPR1J5UWxGS09VOXFZeTA1U1RBNE1WWk1lbGxRUW1oTVlXTkNORkpJZDJKVVRVUkdiVGhvUmtKc1R6bHNkalpqTm5wMU15MXFhMncwU2xoVGR4SVhabG93TVZwZmVYTk5USFZHZDJKclVERlpWSEEyVVRBYUlrRkdXSEpGWTI5MGJVWlhWMlZqWW5STGNESnVVMHAwYjJWU2RWRktTa2N0VkZFIiwiZmN2IjoiMyIsImVpIjoiZlowMVpfeXNNTHVGd2JrUDFZVHA2UTAiLCJxYyI6IkNqTjNhR0YwSUdseklIUm9aU0JpWlhOMElIZGhlU0IwYnlCamIyMXRkVzVwWTJGMFpTQjBhR1Z6WlNCdGFXTnliM052Wm5RUUFIMFYzVElfIiwicXVlc3Rpb24iOiJIb3cgZG8gTWljcm9zb2Z0IGVtcGxveWVlcyBjb21tdW5pY2F0ZT8iLCJsayI6IkdpWm9iM2NnWkc4Z2JXbGpjbTl6YjJaMElHVnRjR3h2ZVdWbGN5QmpiMjF0ZFc1cFkyRjBaUSIsImJzIjoiYzRYUHNRckNNQkFHWU56a0pzZVE2UWJidXFqUVhiTHE0Q0pGNTlLa0pHQjZ4YVNVanI2QWItYTctQWkycUxTaTZQN2RfXzhIT3dqV1ZHT1dGcmpCakt5dENwT2xYbUZ0dk1hdHlVN2tLUGVDWFdVYzhxbC1Xdk5wN2N1Q2hNVkJweDU5VXlxa2ZFQU5GU2hKdVQ0WUs2Y0V1elh4a3NfclAwZDJlQVI3aUxybGtnWmh5cFpIYWxSckJfTUVPNl9pR1FfMVE5dmZHaElJdTF4UGJ5LTJHX3FhUktYV0NYWVp4eEVQOUZmY3RfZ09UMFozIiwiaWQiOiJmY19mWjAxWl95c01MdUZ3YmtQMVlUcDZRMF8xIn0=",
            "serpapi_link": "https://serpapi.com/search.json?device=desktop&engine=google_related_questions&google_domain=google.com&next_page_token=eyJvbnMiOiIxMDA0MSIsImZjIjoiRXFFQkNtSkJTa2M1U210TlRUaFlPRlJYTTFObGRrb3RkbDh5Vm5OVFQwcG9SRkV3WTFGT1VsOXlPR1J5UWxGS09VOXFZeTA1U1RBNE1WWk1lbGxRUW1oTVlXTkNORkpJZDJKVVRVUkdiVGhvUmtKc1R6bHNkalpqTm5wMU15MXFhMncwU2xoVGR4SVhabG93TVZwZmVYTk5USFZHZDJKclVERlpWSEEyVVRBYUlrRkdXSEpGWTI5MGJVWlhWMlZqWW5STGNESnVVMHAwYjJWU2RWRktTa2N0VkZFIiwiZmN2IjoiMyIsImVpIjoiZlowMVpfeXNNTHVGd2JrUDFZVHA2UTAiLCJxYyI6IkNqTjNhR0YwSUdseklIUm9aU0JpWlhOMElIZGhlU0IwYnlCamIyMXRkVzVwWTJGMFpTQjBhR1Z6WlNCdGFXTnliM052Wm5RUUFIMFYzVElfIiwicXVlc3Rpb24iOiJIb3cgZG8gTWljcm9zb2Z0IGVtcGxveWVlcyBjb21tdW5pY2F0ZT8iLCJsayI6IkdpWm9iM2NnWkc4Z2JXbGpjbTl6YjJaMElHVnRjR3h2ZVdWbGN5QmpiMjF0ZFc1cFkyRjBaUSIsImJzIjoiYzRYUHNRckNNQkFHWU56a0pzZVE2UWJidXFqUVhiTHE0Q0pGNTlLa0pHQjZ4YVNVanI2QWItYTctQWkycUxTaTZQN2RfXzhIT3dqV1ZHT1dGcmpCakt5dENwT2xYbUZ0dk1hdHlVN2tLUGVDWFdVYzhxbC1Xdk5wN2N1Q2hNVkJweDU5VXlxa2ZFQU5GU2hKdVQ0WUs2Y0V1elh4a3NfclAwZDJlQVI3aUxybGtnWmh5cFpIYWxSckJfTUVPNl9pR1FfMVE5dmZHaElJdTF4UGJ5LTJHX3FhUktYV0NYWVp4eEVQOUZmY3RfZ09UMFozIiwiaWQiOiJmY19mWjAxWl95c01MdUZ3YmtQMVlUcDZRMF8xIn0%3D",
        },
        {
            "question": "How to communicate on Microsoft Teams?",
            "snippet": null,
            "title": "Start your meeting",
            "link": "https://support.microsoft.com/en-us/topic/communicate-or-meet-by-using-teams-34dd1c2a-8921-45a5-a22e-60ac515039ce",
            "list": [
                "Select Join.",
                "Check your settings before you start. When you're ready, select Join now. ... ",
                "Once you're in the meeting, select More actions. to Turn on live captions, Show meeting notes, or Start recording. ... ",
                "Use the menu bar to select controls to Share your screen, Mute your microphone, or Show conversation.",
            ],
            "displayed_link": "https://support.microsoft.com › en-us › topic › communi...",
            "source_logo": null,
            "next_page_token": "eyJvbnMiOiIxMDA0MSIsImZjIjoiRXFFQkNtSkJTa2M1U210TlRUaFlPRlJYTTFObGRrb3RkbDh5Vm5OVFQwcG9SRkV3WTFGT1VsOXlPR1J5UWxGS09VOXFZeTA1U1RBNE1WWk1lbGxRUW1oTVlXTkNORkpJZDJKVVRVUkdiVGhvUmtKc1R6bHNkalpqTm5wMU15MXFhMncwU2xoVGR4SVhabG93TVZwZmVYTk5USFZHZDJKclVERlpWSEEyVVRBYUlrRkdXSEpGWTI5MGJVWlhWMlZqWW5STGNESnVVMHAwYjJWU2RWRktTa2N0VkZFIiwiZmN2IjoiMyIsImVpIjoiZlowMVpfeXNNTHVGd2JrUDFZVHA2UTAiLCJxYyI6IkNqTjNhR0YwSUdseklIUm9aU0JpWlhOMElIZGhlU0IwYnlCamIyMXRkVzVwWTJGMFpTQjBhR1Z6WlNCdGFXTnliM052Wm5RUUFIMFYzVElfIiwicXVlc3Rpb24iOiJIb3cgdG8gY29tbXVuaWNhdGUgb24gTWljcm9zb2Z0IFRlYW1zPyIsImxrIjoiR2lWb2IzY2dkRzhnWTI5dGJYVnVhV05oZEdVZ2IyNGdiV2xqY205emIyWjBJSFJsWVcxeiIsImJzIjoiYzRYUHNRckNNQkFHWU56a0pzZVE2UWJidXFqUVhiTHE0Q0pGNTlLa0pHQjZ4YVNVanI2QWItYTctQWkycUxTaTZQN2RfXzhIT3dqV1ZHT1dGcmpCakt5dENwT2xYbUZ0dk1hdHlVN2tLUGVDWFdVYzhxbC1Xdk5wN2N1Q2hNVkJweDU5VXlxa2ZFQU5GU2hKdVQ0WUs2Y0V1elh4a3NfclAwZDJlQVI3aUxybGtnWmh5cFpIYWxSckJfTUVPNl9pR1FfMVE5dmZHaElJdTF4UGJ5LTJHX3FhUktYV0NYWVp4eEVQOUZmY3RfZ09UMFozIiwiaWQiOiJmY19mWjAxWl95c01MdUZ3YmtQMVlUcDZRMF8xIn0=",
            "serpapi_link": "https://serpapi.com/search.json?device=desktop&engine=google_related_questions&google_domain=google.com&next_page_token=eyJvbnMiOiIxMDA0MSIsImZjIjoiRXFFQkNtSkJTa2M1U210TlRUaFlPRlJYTTFObGRrb3RkbDh5Vm5OVFQwcG9SRkV3WTFGT1VsOXlPR1J5UWxGS09VOXFZeTA1U1RBNE1WWk1lbGxRUW1oTVlXTkNORkpJZDJKVVRVUkdiVGhvUmtKc1R6bHNkalpqTm5wMU15MXFhMncwU2xoVGR4SVhabG93TVZwZmVYTk5USFZHZDJKclVERlpWSEEyVVRBYUlrRkdXSEpGWTI5MGJVWlhWMlZqWW5STGNESnVVMHAwYjJWU2RWRktTa2N0VkZFIiwiZmN2IjoiMyIsImVpIjoiZlowMVpfeXNNTHVGd2JrUDFZVHA2UTAiLCJxYyI6IkNqTjNhR0YwSUdseklIUm9aU0JpWlhOMElIZGhlU0IwYnlCamIyMXRkVzVwWTJGMFpTQjBhR1Z6WlNCdGFXTnliM052Wm5RUUFIMFYzVElfIiwicXVlc3Rpb24iOiJIb3cgdG8gY29tbXVuaWNhdGUgb24gTWljcm9zb2Z0IFRlYW1zPyIsImxrIjoiR2lWb2IzY2dkRzhnWTI5dGJYVnVhV05oZEdVZ2IyNGdiV2xqY205emIyWjBJSFJsWVcxeiIsImJzIjoiYzRYUHNRckNNQkFHWU56a0pzZVE2UWJidXFqUVhiTHE0Q0pGNTlLa0pHQjZ4YVNVanI2QWItYTctQWkycUxTaTZQN2RfXzhIT3dqV1ZHT1dGcmpCakt5dENwT2xYbUZ0dk1hdHlVN2tLUGVDWFdVYzhxbC1Xdk5wN2N1Q2hNVkJweDU5VXlxa2ZFQU5GU2hKdVQ0WUs2Y0V1elh4a3NfclAwZDJlQVI3aUxybGtnWmh5cFpIYWxSckJfTUVPNl9pR1FfMVE5dmZHaElJdTF4UGJ5LTJHX3FhUktYV0NYWVp4eEVQOUZmY3RfZ09UMFozIiwiaWQiOiJmY19mWjAxWl95c01MdUZ3YmtQMVlUcDZRMF8xIn0%3D",
        },
    ],
    "organic_results": [
        {
            "position": 1,
            "title": "How to communicate with Microsoft?",
            "link": "https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-communicate-with-microsoft/1045f3b0-3b72-4cee-925c-ebb1ad2b5c22",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-communicate-with-microsoft/1045f3b0-3b72-4cee-925c-ebb1ad2b5c22&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECB8QAQ",
            "displayed_link": "https://answers.microsoft.com › msoffice › forum › all",
            "favicon": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/643aff474c990bc2edde40ec4597ed0ef3fecb4b4ea3451077450b559044a5ea.png",
            "date": "Jan 7, 2023",
            "snippet": "You can communicate with Microsoft support through the live chat using the steps below: 1. Go to http://support.office.com/home/chat 2. Describe your issue and ...",
            "snippet_highlighted_words": ["communicate", "Microsoft"],
            "missing": ["these"],
            "must_include": {
                "word": "these",
                "link": "https://www.google.com/search?sca_esv=2b265522246b066d&q=what+is+the+best+way+to+communicate+%22these%22+Microsoft&sa=X&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q5t4CegQIJxAB",
            },
            "source": "Microsoft Community",
        },
        {
            "position": 2,
            "title": "How do you communicate with Microsoft?",
            "link": "https://answers.microsoft.com/en-us/msoffice/forum/all/how-do-you-communicate-with-microsoft/0e214953-55e6-49f8-9335-6a2fcadac078",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://answers.microsoft.com/en-us/msoffice/forum/all/how-do-you-communicate-with-microsoft/0e214953-55e6-49f8-9335-6a2fcadac078&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECDMQAQ",
            "displayed_link": "https://answers.microsoft.com › msoffice › forum › all",
            "favicon": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/643aff474c990bc2edde40ec4597ed0e89e7ce4f2cd358e02dcf100485875e2e.png",
            "date": "Jun 3, 2021",
            "snippet": "Microsoft hires third party companies for support providing. You may find support contact phones at https://support.microsoft.com/en-us/help/ ...",
            "snippet_highlighted_words": ["Microsoft", "microsoft"],
            "missing": ["these"],
            "must_include": {
                "word": "these",
                "link": "https://www.google.com/search?sca_esv=2b265522246b066d&q=what+is+the+best+way+to+communicate+%22these%22+Microsoft&sa=X&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q5t4CegQIRBAB",
            },
            "source": "Microsoft Community",
        },
        {
            "position": 3,
            "title": "Communicate or meet by using Teams",
            "link": "https://support.microsoft.com/en-us/topic/communicate-or-meet-by-using-teams-34dd1c2a-8921-45a5-a22e-60ac515039ce",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://support.microsoft.com/en-us/topic/communicate-or-meet-by-using-teams-34dd1c2a-8921-45a5-a22e-60ac515039ce&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECDQQAQ",
            "displayed_link": "https://support.microsoft.com › en-us › topic › communi...",
            "snippet": "Microsoft Teams is the messaging app for your organization—a workspace for meetings, real-time collaboration and communication, and file and app sharing.",
            "snippet_highlighted_words": ["Microsoft", "communication"],
            "sitelinks": {
                "inline": [
                    {
                        "title": "Have Your Meetings In Teams",
                        "link": "https://support.microsoft.com/en-us/topic/communicate-or-meet-by-using-teams-34dd1c2a-8921-45a5-a22e-60ac515039ce#:~:text=Have%20your%20meetings%20in%20Teams",
                    },
                    {
                        "title": "Start Your Meeting",
                        "link": "https://support.microsoft.com/en-us/topic/communicate-or-meet-by-using-teams-34dd1c2a-8921-45a5-a22e-60ac515039ce#:~:text=Start%20your%20meeting",
                    },
                    {
                        "title": "Work In Teams And Channels",
                        "link": "https://support.microsoft.com/en-us/topic/communicate-or-meet-by-using-teams-34dd1c2a-8921-45a5-a22e-60ac515039ce#:~:text=Work%20in%20teams%20and%20channels",
                    },
                ]
            },
            "missing": ["these"],
            "must_include": {
                "word": "these",
                "link": "https://www.google.com/search?sca_esv=2b265522246b066d&q=what+is+the+best+way+to+communicate+%22these%22+Microsoft&sa=X&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q5t4CegQIQxAB",
            },
            "source": "Microsoft Support",
        },
        {
            "position": 4,
            "title": "Best practices for managers about efficient communication",
            "link": "https://learn.microsoft.com/en-us/previous-versions/viva/insights/tutorials/gm-communication",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://learn.microsoft.com/en-us/previous-versions/viva/insights/tutorials/gm-communication&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECDIQAQ",
            "displayed_link": "https://learn.microsoft.com › insights › gm-communication",
            "favicon": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/643aff474c990bc2edde40ec4597ed0e06f635417b27b2f746a387366e42b916.png",
            "date": "Nov 30, 2023",
            "snippet": "Create a Teams channel or an email thread that recognizes teammates who migrate conversations to teams, resulting in time savings.",
            "sitelinks": {
                "inline": [
                    {
                        "title": "Why It Matters",
                        "link": "https://learn.microsoft.com/en-us/previous-versions/viva/insights/tutorials/gm-communication#:~:text=Why%20it%20matters,-Based%20on%20the%20information%20presented",
                    },
                    {
                        "title": "Best Practices",
                        "link": "https://learn.microsoft.com/en-us/previous-versions/viva/insights/tutorials/gm-communication#:~:text=Best%20practices,-Showcase%20the%20value%20in%20utilizing",
                    },
                    {
                        "title": "Change Strategies",
                        "link": "https://learn.microsoft.com/en-us/previous-versions/viva/insights/tutorials/gm-communication#:~:text=Change%20strategies,-Be%20a%20role%20model%20for",
                    },
                ]
            },
            "source": "Microsoft Learn",
        },
        {
            "position": 5,
            "title": "M365: Strategies and Tools for Effective Communication in ...",
            "link": "https://www.doherty.co.uk/blog/m365-strategies-and-tools-for-effective-communication-in-the-modern-workplace/",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.doherty.co.uk/blog/m365-strategies-and-tools-for-effective-communication-in-the-modern-workplace/&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECDAQAQ",
            "displayed_link": "https://www.doherty.co.uk › blog › m365-strategies-an...",
            "favicon": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/643aff474c990bc2edde40ec4597ed0e83dd32a7905ee9f355464891f1547bd7.png",
            "date": "Jan 23, 2024",
            "snippet": "M365 gives businesses all the tools they need to get their teams communicating, collaborating and driving success together.",
            "snippet_highlighted_words": ["communicating"],
            "source": "Doherty Associates",
        },
        {
            "position": 6,
            "title": "How do I communicate with MICROSOFT Support?",
            "link": "https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-communicate-with-microsoft-support/e690a9c3-610b-4fcb-bda3-6f42a194517a",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-communicate-with-microsoft-support/e690a9c3-610b-4fcb-bda3-6f42a194517a&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECC0QAQ",
            "displayed_link": "https://answers.microsoft.com › windows › forum › all",
            "favicon": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/643aff474c990bc2edde40ec4597ed0e7908393167b1eabcadd312efb22a9e12.png",
            "date": "Feb 26, 2018",
            "snippet": "Instead, what Microsoft has is a 'train-the-trainer' setup, whereby it trains third-parties to go out and provide the support that people need.",
            "snippet_highlighted_words": ["Microsoft"],
            "source": "Microsoft Community",
        },
        {
            "position": 7,
            "title": "How your company can efficiently use Microsoft 365 tools",
            "link": "https://rencore.com/en/blog/communication-collaboration-microsoft-tools/",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://rencore.com/en/blog/communication-collaboration-microsoft-tools/&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECCwQAQ",
            "displayed_link": "https://rencore.com › blog › communication-collaborati...",
            "favicon": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/643aff474c990bc2edde40ec4597ed0e5ad410c4d187f59b49ec144b925a4ae9.png",
            "snippet": "In Microsoft 365 alone, we have several communication tools, including Outlook (e-mail), SharePoint (intranet), Teams and Viva Engage (ex-Yammer).",
            "snippet_highlighted_words": ["Microsoft", "communication"],
            "source": "Rencore Governance",
        },
        {
            "position": 8,
            "title": "How do I communicate CLEARLY with These People?",
            "link": "https://answers.microsoft.com/en-us/msoffice/forum/all/how-do-i-communicate-clearly-with-these-people/0c4dd02e-a9e5-4e70-b0a6-38989e1724ba",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://answers.microsoft.com/en-us/msoffice/forum/all/how-do-i-communicate-clearly-with-these-people/0c4dd02e-a9e5-4e70-b0a6-38989e1724ba&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECC4QAQ",
            "displayed_link": "https://answers.microsoft.com › msoffice › forum › all",
            "favicon": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/643aff474c990bc2edde40ec4597ed0e50ec2a898f94d79bfefff2c631f64a67.png",
            "date": "Nov 2, 2023",
            "snippet": "I suggest that you try the telephone here: Global Customer Service phone numbers - Microsoft Support (Not sure about times over Christmas and ...",
            "snippet_highlighted_words": ["Microsoft"],
            "source": "Microsoft Community",
        },
        {
            "position": 9,
            "title": "Communicate like a pro using Microsoft Teams - Storyals Blog",
            "link": "https://blog.storyals.com/communicate-like-pro-using-microsoft-teams",
            "redirect_link": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://blog.storyals.com/communicate-like-pro-using-microsoft-teams&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0QFnoECDEQAQ",
            "displayed_link": "https://blog.storyals.com › communicate-like-pro-using...",
            "favicon": "https://serpapi.com/searches/67359d7c66d9950a646e29eb/images/643aff474c990bc2edde40ec4597ed0ec017cae9853147666dd064eff140fb9e.png",
            "snippet": "In this blog/vlog, Ulrika Hedlund shares her experiences to help you communicate like a pro using Microsoft Teams split into five parts.",
            "snippet_highlighted_words": ["this", "communicate", "Microsoft"],
            "sitelinks": {
                "inline": [
                    {
                        "title": "Part 1 -- Understand What...",
                        "link": "https://blog.storyals.com/communicate-like-pro-using-microsoft-teams#:~:text=Part%201%20%2D%2D%20Understand%20what%20type%20of%20messaging%20to%20use%20when",
                    },
                    {
                        "title": "Part 4 -- Select Which...",
                        "link": "https://blog.storyals.com/communicate-like-pro-using-microsoft-teams#:~:text=Part%204%20%2D%2D%20Select%20which%20channels%20you%20want%20to%20engage%20in",
                    },
                    {
                        "title": "Part 5 -- Actively Use Your...",
                        "link": "https://blog.storyals.com/communicate-like-pro-using-microsoft-teams#:~:text=Part%205%20%2D%2D%20Actively%20use%20your%20presence%20to%20show%20your%20availability",
                    },
                ]
            },
            "source": "Storyals",
        },
    ],
    "related_searches": [
        {
            "block_position": 1,
            "query": "What is the best way to communicate these microsoft windows 10",
            "link": "https://www.google.com/search?sca_esv=2b265522246b066d&q=What+is+the+best+way+to+communicate+these+microsoft+windows+10&sa=X&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q1QJ6BAg2EAE",
            "serpapi_link": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=What+is+the+best+way+to+communicate+these+microsoft+windows+10",
        },
        {
            "block_position": 1,
            "query": "What is the best way to communicate these microsoft 365",
            "link": "https://www.google.com/search?sca_esv=2b265522246b066d&q=What+is+the+best+way+to+communicate+these+microsoft+365&sa=X&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q1QJ6BAg1EAE",
            "serpapi_link": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=What+is+the+best+way+to+communicate+these+microsoft+365",
        },
        {
            "block_position": 1,
            "query": "What is the best way to communicate these microsoft 2021",
            "link": "https://www.google.com/search?sca_esv=2b265522246b066d&q=What+is+the+best+way+to+communicate+these+microsoft+2021&sa=X&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q1QJ6BAgvEAE",
            "serpapi_link": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=What+is+the+best+way+to+communicate+these+microsoft+2021",
        },
    ],
    "pagination": {
        "current": 1,
        "next": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=10&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8NMDegQICBAW",
        "other_pages": {
            "2": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=10&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAE",
            "3": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=20&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAG",
            "4": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=30&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAI",
            "5": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=40&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAK",
            "6": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=50&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAM",
            "7": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=60&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAO",
            "8": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=70&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAQ",
            "9": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=80&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAS",
            "10": "https://www.google.com/search?q=what+is+the+best+way+to+communicate+these+Microsoft&sca_esv=2b265522246b066d&ei=fZ01Z_ysMLuFwbkP1YTp6Q0&start=90&sa=N&sstk=ATObxK5k-ZowFGqGhaYuraCGUyHv44lUvWxqk5-ZOVpOzLcy5Sn8V3sarvgot_183Ktpqa6NifQBwl-rqJKnKrGQOQoqvbqGyVjNAw&ved=2ahUKEwi834LTnduJAxW7QjABHVVCOt0Q8tMDegQICBAU",
        },
    },
    "serpapi_pagination": {
        "current": 1,
        "next_link": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=10",
        "next": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=10",
        "other_pages": {
            "2": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=10",
            "3": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=20",
            "4": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=30",
            "5": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=40",
            "6": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=50",
            "7": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=60",
            "8": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=70",
            "9": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=80",
            "10": "https://serpapi.com/search.json?device=desktop&engine=google&google_domain=google.com&q=what+is+the+best+way+to+communicate+these+Microsoft&start=90",
        },
    },
}
